---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - propeller.absmach.io
  resources:
  - federatedjobs
  - trainingrounds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - propeller.absmach.io
  resources:
  - federatedjobs/status
  - trainingrounds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - propeller.propeller.abstractmachines.fr
  resources:
  - proplets
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - propeller.propeller.abstractmachines.fr
  resources:
  - proplets/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - propeller.propeller.abstractmachines.fr
  resources:
  - proplets/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
