apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proplet
  namespace: default
  labels:
    app: k8s-proplet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-proplet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: k8s-proplet
    spec:
      restartPolicy: Always

      containers:
        - name: k8s-proplet
          image: docker.io/rodneydav/propeller-k8s-operator-proplet:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: PROPLET_LOG_LEVEL
              value: info
            - name: PROPLET_MQTT_ADDRESS
              value: "tcp://0.tcp.in.ngrok.io:16621"
            - name: PROPLET_MQTT_QOS
              value: "1"
            - name: PROPLET_MQTT_TIMEOUT
              value: 10s
            - name: PROPLET_LIVELINESS_INTERVAL
              value: "5s"
            - name: PROPLET_DOMAIN_ID
              value: cbba98e5-84a9-422c-ad00-f6ee21d6695a
            - name: PROPLET_CHANNEL_ID
              value: 16722ec1-ce8a-446d-a829-d83459f1c40e
            - name: PROPLET_CLIENT_ID
              value: ef007c37-3253-4860-9986-cc9262a8e0f1
            - name: PROPLET_CLIENT_KEY
              value: b07514e4-05a6-40bc-acde-3030e757839c
