apiVersion: propeller.propeller.absmach.eu/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: propeller-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: broadcast-task
spec:
  name: broadcast-task
  functionName: main
  kind: standard
  file: "AGFzbQEAAAABBwFgAn9/AX8DAgEABwgBBG1haW4AAAoJAQcAIAAgAWoL"
  inputs:
    - "10"
    - "32"
  broadcast: true
  daemon: false
  priority: 50
