apiVersion: propeller.propeller.absmach.eu/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: propeller-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: wasm-addition-from-registry
spec:
  name: wasm-addition-from-registry
  functionName: add
  kind: standard
  imageUrl: "docker.io/mrstevenyaga/add.wasm:latest"
  inputs:
    - 10
    - 89
  mode: infer
  daemon: false
  priority: 50
  propletSelector:
    propletId: "external-proplet"
