apiVersion: propeller.propeller.absmach.eu/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: propeller-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: wasm-addition
spec:
  name: wasm-addition
  functionName: main
  kind: standard
  file: "AGFzbQEAAAABBwFgAn9/AX8DAgEABwgBBG1haW4AAAoJAQcAIAAgAWoL"
  inputs:
    - "10"
    - "32"
  daemon: false
  propletSelector:
    propletId: "k8s-proplet"
