apiVersion: propeller.propeller.absmach.eu/v1
kind: Proplet
metadata:
  labels:
    app.kubernetes.io/name: propeller-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: external-proplet
spec:
  type: external
  external:
    deviceType: "docker-container"
    capabilities:
      - wasm
      - wasmtime
  connectionConfig:
    tenantId: "<your-tenant-id>"
    channelId: "<your-channel-id>"
    entityId: "<your-proplet-entity-id>"
    apiKey: "<your-proplet-api-key>"
    mqttAddress: "tcp://your-mqtt-broker:1883"
    mqttQos: 0
    mqttTimeout: 30s
