apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proxy
  namespace: default
  labels:
    app: k8s-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: k8s-proxy
    spec:
      restartPolicy: Always

      containers:
        - name: k8s-proxy
          image: docker.io/rodneydav/propeller-k8s-operator-proxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
          env:
            - name: PROXY_LOG_LEVEL
              value: info
            - name: PROXY_MQTT_ADDRESS
              value: tcp://0.tcp.in.ngrok.io:16621
            - name: PROXY_MQTT_QOS
              value: "1"
            - name: PROXY_MQTT_TIMEOUT
              value: 10s
            - name: PROXY_LIVELINESS_INTERVAL
              value: 5s
            - name: PROXY_DOMAIN_ID
              value: cbba98e5-84a9-422c-ad00-f6ee21d6695a
            - name: PROXY_CHANNEL_ID
              value: 16722ec1-ce8a-446d-a829-d83459f1c40e
            - name: PROXY_CLIENT_ID
              value: ef007c37-3253-4860-9986-cc9262a8e0f1
            - name: PROXY_CLIENT_KEY
              value: b07514e4-05a6-40bc-acde-3030e757839c
            - name: PROXY_CHUNK_SIZE
              value: "512000"
            - name: PROXY_AUTHENTICATE
              value: "TRUE"
            - name: PROXY_REGISTRY_USERNAME
              value: "rodneydav"
            - name: PROXY_REGISTRY_PASSWORD
              value: "dckr_pat_-Ebj5-YTMyr8wPaPESxWJmRGZXI"
            - name: PROXY_REGISTRY_URL
              value: "docker.io"
