apiVersion: propeller.propeller.absmach.eu/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: propeller-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: dag-task-b
spec:
  name: dag-task-b
  functionName: main
  kind: standard
  file: "AGFzbQEAAAABBwFgAn9/AX8DAgEABwgBBG1haW4AAAoJAQcAIAAgAWoL"
  inputs:
    - "5"
    - "15"
  dependsOn:
    - "dag-task-a"
  runIf: success
  workflowId: "my-dag-workflow"
  mode: infer
  daemon: false
  priority: 50
  propletSelector:
    propletId: "external-proplet"
